### ISSUE TITLE
Prefabs

### ISSUE THREAD

**Issue by EGAMatsu** [deadcast2/UltraEd#134]
Prefabs are a way to store objects that are the same in every map/scene, if this will be a full engine, that is a good step.
...Also multi texture meshes, Ive not seen if they are in here yet, but if they are not, it would be a life saver.

**Comment by deadcast2** [comment]
Yeah those would be very nice features to have in UltraEd. I don't think the N64 supports multi texturing but it could be done in a way by combining various meshes. Some textured and some vertex colored. That scenario would be perfect for prefabs since you could construct an advanced model. Like how I think Mario was done in Super Mario 64.
