### ISSUE TITLE
Suggestion: Add following lines to fix build ROM issue on some machines

### ISSUE THREAD

**Issue by Lizband** [deadcast2/UltraEd#144]
Myself and several others would see no change to the game unless the original built ROM files were deleted after each attempt to build. Adding these lines to the start of the build.bat file in `UltraEd/Engine` fixes this issue. Please add this change to future commits!
```
del ".\main.n64"
del ".\main.o"
del ".\main.out"
SET PATH=%PATH%;%ROOT%
call setupgcc.bat
make clean
make
```

**Comment by deadcast2** [comment]
Ok done! I actually made the modification to the common rules file in the sdk folder so `make clean` would be responsible for deletion. Just like for *.o files. So once you pull down the latest changes you'll have to reinstall the build tools since the file modified lives in there. If you have any issue let me know and hopefully this makes life easier in UltraEd.

![Untitled](https://user-images.githubusercontent.com/45521946/150903354-83489e14-2ecb-4567-960a-d19c5bb3a576.png)
