### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Bloxxel64** [deadcast2/UltraEd#158]
I'm a Linux guy mainly and would love to try this revolutionary piece of software. I would be glad to test if I can.

**Comment by deadcast2** [comment]
Hello!

Glad to hear you're interested in UltraEd. Linux support is sadly pretty far away right now. I would like to not have to rely on windows but a big change I'd have to do is replace the editor's renderer with OpenGL. I plan on doing that conversion someday and then the toolchain I'd have to recompile for a different target. Those I think are the only big changes that need to happen in order to have UltraEd start running on different operating systems. I guess you could try using Wine to run UltraEd but you'd still have to compile it first which right now it's tightly configured to use visual studio. Getting off the dependency to use windows would be great! Maybe I need to start thinking more about that since I have no interest currently to upgrade to win 11 lol.
