### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by SuperSquidlit** [deadcast2/UltraEd#170]
Hello!
How would I go about using an animation? What type of file should I export one as or are we just moving vertices?

Thank you for making this wonderful thing!

**Comment by deadcast2** [comment]
Hey! Unfortunately, no animations are supported right now. Definitely on the todo list but I'm spread a little thin currently. I probably should add to the readme what features currently aren't support to not get peoples' hopes up too high since this project is still pretty feature lacking. :) I'm glad you like the project and what it can do so far!

**Comment by SuperSquidlit** [comment]
Thank you for the info! I understand how it gets haha.
Honestly I’m having lots of fun with what’s available. Can’t wait to see whatever’s added next!
