### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by honzapatCZ** [deadcast2/UltraEd#38]
First I really like what you do and hope I can help you with the code once I have some time, but Ive read somewhere you want it feel like Unity, that means with added features using the add button separative on top will get tidius really quickly so there could be implemented the Inspector window, precise editing of transform and adding separate componenets, will take a look at it myself and hope we can make this the firat true universal engine.

**Comment by deadcast2** [comment]
@honzapatCZ Hello! Great to hear you like UltraEd and are willing to help in the future. Yeah my original idea was for the editor to work sort of like Unity with the component system. I like the idea of starting with a simple game object and then adding the needed functionality. The "Add" menu I know needs some work and I've been adding more features to the right-click menu. Definitely the Inspector Window is something needed pretty bad since there's only the gizmo currently to manipulate actors in the scene. Would also like to get the collision stuff finally done too. Lol lots of things to do when building an editor. Didn't total realize that I guess. :)
