### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by nterry** [deadcast2/UltraEd#81]
Hey, I'm just wondering why you changed the license from the MIT license to the GPL, a _highly infective_ license. Are you dead-set on the GPL? Would you consider the LGPL instead? Or better, the MIT or apache 2 license?

There's code of yours Id LOVE to use, but I don't want to be forced into the GPL myself, especially given that it's incompatible with a LOT of other licenses.

**Comment by deadcast2** [comment]
Hello! I actually just changed the license back to MIT. I think I changed to GPL when I was porting to use the open source version of Qt and wanted to have a compatible license. Since I'm not using Qt now but ImGui instead I guess there's no reason to be GPL lol. I am curious to know what you mean by GPL being "highly infective?" Licenses are still a bit confusing sometimes. Glad to hear you like some of the code in UltraEd! It has come a long way and I still have much to do. :)

**Comment by nterry** [comment]
"Highly infective" is a term applied to the GPL because it requires you apply the same terms to ALL of your code. You cant use ANY proprietary code because you have to release ALL the source code.

You have to be SUPER careful because if you introduce ANY code that is licensed by the GPL, even by accident, you're screwed. You either have to remove that code, or re-license the whole thing under the GPL.

I'm glad you went back to the MIT license ;) Its far more free and conducive to innovation.

**Comment by deadcast2** [comment]
Thank you very much for your insightful response. Makes sense and I appreciate it! Yeah sometimes I take licenses too relaxed-like but should definitely pay more attention. I like the idea of adding additional info to the readme for why I moved back to the MIT license from GPL v3. I'll amend it.

Thanks again!
