### ISSUE TITLE
REQUEST: create a manual + build

### ISSUE THREAD

**Issue by starinspace** [deadcast2/UltraEd#85]
Is it possible for you to create a small manual? It's a bit hard to figure out how some things works, what I want to see in a manual is how to do from ground:

1. Create a easy figure with legs.
2. How to move/animate the legs and jump/go down on knee (or something)
3. Create environment/room/cave that can not be crossed.
4. How to die and point where to start if dead.
5. Shooting a weapon.
6. Adding textures and what format/size is ok and how to add shadows.

I think that would be a good basic things to know and to get started.

And a build so it's easier to run. (I don't have internet access for the computer i do things on and not able to install visual studio on the other.)

**Comment by deadcast2** [comment]
Hello and thanks for checking out UltraEd!

Yes a small manual would be very nice and I have plans on writing one eventually. I've been putting that off since I'm first trying to successfully build my own very small game with UltraEd to make sure a first official release has enough adequate functionality. I'm currently in-process with creating a parent/child system for objects and making progress.

There's currently no animation system implemented and also no audio support yet. I've been mostly busy just trying to write a good UI. Everything you mentioned besides the animation is what I'm attempting to build myself. Once I have this little "Tank" game I'm developing the source will be included with UltraEd. That should help to get yourself familiar with what is capable.

So UltraEd isn't quite just ready to be fully used unfortunately. I multitask between various other projects so feature development is a little slow currently.
